MESSAGE_TYPE_MOVE_REQUEST = 0
MESSAGE_TYPE_MOVE_UNITS = 1
MESSAGE_TYPE_NEW_UNITS = 2
MESSAGE_TYPE_MOVE_IN_RANGE_REQUEST = 3
MESSAGE_TYPE_ATTACK_REQUEST = 4
MESSAGE_TYPE_DAMAGE_UPDATE = 5
MESSAGE_TYPE_INIT_GAME = 6
MESSAGE_NUM_TYPES = 7
